# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dotnet tool install Swashbuckle.AspNetCore.Cli -g --version 6.2.3'

- task: CmdLine@2
  inputs:
    script: 'find . -type f'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'swagger tofile --output swagger.json Library\bin\Release\net5.0\Library.dll v1'